#!/usr/bin/env bash

./generate.py build && rm -fr ../ar/ && cp *.txt build && cp source/resource/auroral_resources/favico.ico build && cp -pR build ../ar && cp -pR inspector ../ar/ && cp source/inspector.html ../ar/
