#!/usr/bin/env bash

QXOPTS="-s" #-v verbose -s exception stack trace on fatal error

rm -fr google-appengine/art &&\
rm -fr ar &&\
rm -fr build &&\
./generate.py ${QXOPTS} translation &&\
./generate.py ${QXOPTS} default &&\
./generate.py ${QXOPTS} compress &&\
mv build google-appengine/art &&\
find google-appengine/art/ -name '.svn' | xargs rm -fr &&\
appcfg.py update google-appengine &&\
rm -fr google-appengine/art &&\
echo "w00t" &&\
exit 0

echo "UH OH!"
exit 1
