#!/usr/bin/env bash

rm -fr ../ar/art &&\
rm -fr build &&\
./generate.py build &&\
cp -pR build ../ar/art &&\
cp -pR inspector ../ar/art/ &&\
cp source/inspector.html ../ar/art &&\
find ../ar/art -name '.svn' | xargs rm -fr &&\
cp -pR api ../ar/ &&\
echo "w00t"