#!/usr/bin/env bash

QXOPTS="-s" #-v verbose -s exception stack trace on fatal error

find . -name '.DS_Store' | xargs rm &&\
rm -fr ../ar/art &&\
rm -fr build &&\
./generate.py ${QXOPTS} default &&\
./generate.py ${QXOPTS} compress &&\
cp -pR build ../ar/art &&\
find ../ar/art -name '.svn' | xargs rm -fr &&\
echo "w00t"
